[ 2024-12-23 20:21:33,955 ] 22 root - INFO - Data Ingestion has been started
[ 2024-12-23 20:21:33,956 ] 24 root - INFO - Data reading using Pandas from local file system
[ 2024-12-23 20:21:33,974 ] 26 root - INFO - Data reading has been completed
[ 2024-12-23 20:21:34,041 ] 30 root - INFO - Raw data has been stored
[ 2024-12-23 20:21:34,045 ] 33 root - INFO - Raw data has been splitted into train and test set
[ 2024-12-23 20:21:34,102 ] 38 root - INFO - Data has been completed
[ 2024-12-23 20:21:34,103 ] 50 root - INFO - Created feature store configuration at /home/azim/mlops-project/feature_repo/feature_store.yaml
[ 2024-12-23 20:21:34,103 ] 54 root - INFO - Configuration file content:
project: income_prediction
provider: local
registry: data/registry.db
online_store:
    type: sqlite
offline_store:
    type: file
entity_key_serialization_version: 2
[ 2024-12-23 20:21:34,117 ] 855 feast.infra.registry.registry - INFO - Registry cache expired, so refreshing
[ 2024-12-23 20:21:34,122 ] 58 root - INFO - Feature store initialized successfully
[ 2024-12-23 20:21:34,142 ] 109 root - INFO - Read train and test data completed
[ 2024-12-23 20:21:34,142 ] 110 root - INFO - Obtaining preprocessing object
[ 2024-12-23 20:21:34,142 ] 66 root - INFO - Data Transformation has been started
[ 2024-12-23 20:21:34,144 ] 124 root - INFO - Applying Preprocessing object on training and testing dataset.
[ 2024-12-23 20:21:34,145 ] 149 root - ERROR - Error in data transformatin: A given column is not a column of the dataframe
[ 2024-12-23 20:21:34,145 ] 52 root - ERROR - 
Error occurred in Python script:
→ File: /home/azim/mlops-project/src/components/data_transformation.py
→ Line number: 126
→ Error message: A given column is not a column of the dataframe
